# Generated by Django 5.0.1 on 2024-02-09 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ASLogObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Объект")),
                (
                    "title_description",
                    models.CharField(max_length=100, verbose_name="Описание объекта"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
            },
        ),
        migrations.CreateModel(
            name="ASLogObjectSub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Электропомещение"),
                ),
                (
                    "title_description",
                    models.CharField(
                        max_length=100, verbose_name="Описание Электропомещения"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Электропомещение",
                "verbose_name_plural": "Электропомещения",
            },
        ),
        migrations.CreateModel(
            name="ASLogProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Проект")),
                (
                    "title_description",
                    models.CharField(max_length=100, verbose_name="Описание проекта"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.CreateModel(
            name="ASLogProjectSub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Механизм")),
                (
                    "title_description",
                    models.CharField(max_length=100, verbose_name="Описание механизма"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Механизм",
                "verbose_name_plural": "Механизмы",
            },
        ),
        migrations.CreateModel(
            name="ASLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_text_title",
                    models.CharField(max_length=100, verbose_name="Заголовок записи"),
                ),
                (
                    "record_text_description",
                    models.CharField(
                        max_length=100, verbose_name="Короткий текст записи"
                    ),
                ),
                (
                    "record_text_full",
                    models.CharField(max_length=100, verbose_name="Текст записи"),
                ),
                (
                    "record_text_full_plc",
                    models.CharField(max_length=100, verbose_name="Текст записи PLC"),
                ),
                (
                    "record_text_full_hmi",
                    models.CharField(max_length=100, verbose_name="Текст записи HMI"),
                ),
                (
                    "record_text_full_hmi_to_plc",
                    models.CharField(
                        max_length=100, verbose_name="Текст записи из HMI в PLC"
                    ),
                ),
                (
                    "record_text_full_plc_to_hmi",
                    models.CharField(
                        max_length=100, verbose_name="Текст записи из PLC в HMI"
                    ),
                ),
                (
                    "record_author",
                    models.CharField(max_length=100, verbose_name="Автор записи"),
                ),
                (
                    "record_data_create",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания записи"
                    ),
                ),
                ("record_slug", models.SlugField(unique=True)),
                (
                    "record_object",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_object",
                        to="as.aslogobject",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "record_object_sub",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_object_sub",
                        to="as.aslogobjectsub",
                        verbose_name="Электропомещение",
                    ),
                ),
                (
                    "record_project",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_project",
                        to="as.aslogproject",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "record_project_sub",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_project_sub",
                        to="as.aslogprojectsub",
                        verbose_name="Механизм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
