# Generated by Django 5.0.1 on 2024-02-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aslog",
            name="record_text_description",
        ),
        migrations.RemoveField(
            model_name="aslog",
            name="record_text_full_hmi",
        ),
        migrations.RemoveField(
            model_name="aslog",
            name="record_text_full_plc",
        ),
        migrations.AddField(
            model_name="aslog",
            name="record_change_location_hmi",
            field=models.BooleanField(
                default="1", max_length=100, verbose_name="Изменение в HMI"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aslog",
            name="record_change_location_plc",
            field=models.BooleanField(
                default="1", max_length=100, verbose_name="Изменение в PLC"
            ),
            preserve_default=False,
        ),
    ]
