# Generated by Django 5.0.1 on 2024-04-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aslog",
            name="record_data_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата создания записи"
            ),
        ),
        migrations.AlterField(
            model_name="aslog",
            name="record_data_create",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания записи"
            ),
        ),
    ]
