# Generated by Django 5.0.1 on 2024-04-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as", "0002_aslog_record_data_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aslog",
            name="record_data_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата редактирования записи"
            ),
        ),
    ]
