# Generated by Django 4.2.1 on 2024-01-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationLog_Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Объект")),
                (
                    "title_description",
                    models.CharField(max_length=100, verbose_name="Описание объекта"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
            },
        ),
        migrations.CreateModel(
            name="AutomationLog_Object_Sub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Электропомещение"),
                ),
                (
                    "title_description",
                    models.CharField(
                        max_length=100, verbose_name="Описание Электропомещения"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Электропомещение",
                "verbose_name_plural": "Электропомещения",
            },
        ),
        migrations.CreateModel(
            name="AutomationLog_Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Проект")),
                (
                    "title_description",
                    models.CharField(max_length=100, verbose_name="Описание проекта"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.CreateModel(
            name="AutomationLog_Project_Sub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Механизм")),
                (
                    "title_description",
                    models.CharField(max_length=100, verbose_name="Описание механизма"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Механизм",
                "verbose_name_plural": "Механизмы",
            },
        ),
        migrations.CreateModel(
            name="Myfiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=100, verbose_name="Отправитель файла"),
                ),
                (
                    "text_to",
                    models.CharField(max_length=100, verbose_name="Получатель файла"),
                ),
                (
                    "remote_ip",
                    models.GenericIPAddressField(
                        verbose_name="IP адрес отправителя файла"
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="upload_file/", verbose_name="Файл"),
                ),
                (
                    "data_create",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата загрузки файла"
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
            },
        ),
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_text_title",
                    models.CharField(max_length=100, verbose_name="Заголовок записи"),
                ),
                (
                    "record_text_description",
                    models.CharField(
                        max_length=100, verbose_name="Короткий текст записи"
                    ),
                ),
                (
                    "record_text_full",
                    models.CharField(max_length=100, verbose_name="Текст записи"),
                ),
                (
                    "record_author",
                    models.CharField(max_length=100, verbose_name="Автор записи"),
                ),
                (
                    "record_data_create",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания записи"
                    ),
                ),
                ("record_slug", models.SlugField(unique=True)),
                (
                    "record_object",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_object",
                        to="main.automationlog_object",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "record_object_sub",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_object_sub",
                        to="main.automationlog_object_sub",
                        verbose_name="Электропомещение",
                    ),
                ),
                (
                    "record_project",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_project",
                        to="main.automationlog_project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "record_project_sub",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_project_sub",
                        to="main.automationlog_project_sub",
                        verbose_name="Механизм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
