# Generated by Django 4.2.9 on 2024-01-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationlog",
            name="record_text_full_hmi",
            field=models.CharField(
                default="record_text_full",
                max_length=100,
                verbose_name="Текст записи HMI",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="automationlog",
            name="record_text_full_hmi_to_plc",
            field=models.CharField(
                default="record_text_full_hmi_to_plc",
                max_length=100,
                verbose_name="Текст записи из HMI в PLC",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="automationlog",
            name="record_text_full_plc",
            field=models.CharField(
                default="record_text_full_plc",
                max_length=100,
                verbose_name="Текст записи PLC",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="automationlog",
            name="record_text_full_plc_to_hmi",
            field=models.CharField(
                default="record_text_full_plc_to_hmi",
                max_length=100,
                verbose_name="Текст записи из PLC в HMI",
            ),
            preserve_default=False,
        ),
    ]
