# Generated by Django 5.0.1 on 2024-03-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_myfiles_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myfiles",
            name="file",
            field=models.FileField(
                upload_to="upload_file/2024-03-18/", verbose_name="Файл"
            ),
        ),
    ]
