# Generated by Django 5.0 on 2024-04-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_myfiles_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myfiles",
            name="file",
            field=models.FileField(
                upload_to="upload_file/2024-04-26/", verbose_name="Файл"
            ),
        ),
    ]
